# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Portfolian' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'GoogleSignIn'
pod 'Then'
pod 'SnapKit'
pod 'KakaoSDKCommon'
pod 'KakaoSDKAuth'
pod 'KakaoSDKUser'
pod 'KakaoSDKTalk'
pod 'Alamofire'
pod 'Toast-Swift'
pod 'SwiftyJSON'
pod 'SwiftyMarkdown'
pod 'Firebase/Analytics'
pod 'Firebase/Messaging'
pod 'MessageKit'
pod 'Socket.IO-Client-Swift'
# pod 'Firebase'
  # Pods for Portfolian`

end
